"""migrate language from user to account

Revision ID: 2608b961c4d3
Revises: 0db8ecf7ed4a
Create Date: 2024-12-23 09:19:49.982317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2608b961c4d3'
down_revision: Union[str, None] = '0db8ecf7ed4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('language', sa.String(length=50), nullable=True))
    op.drop_column('users', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'language')
    # ### end Alembic commands ###
