"""update tenant & account & user & oauth tables

Revision ID: 55db90ca20f2
Revises: 2608b961c4d3
Create Date: 2025-01-15 01:56:23.728655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55db90ca20f2'
down_revision: Union[str, None] = '2608b961c4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_invites',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_invites_code'), 'tenant_invites', ['code'], unique=True)
    op.add_column('accounts', sa.Column('last_login_tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'tenants', ['last_login_tenant_id'], ['id'])
    op.add_column('o_auth_providers', sa.Column('profile_data', sa.JSON(), nullable=True))
    op.alter_column('o_auth_providers', 'access_token',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    op.add_column('tenants', sa.Column('logo', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('invite_code', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'users', 'tenant_invites', ['invite_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invite_code')
    op.drop_column('tenants', 'logo')
    op.alter_column('o_auth_providers', 'access_token',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.drop_column('o_auth_providers', 'profile_data')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'last_login_tenant_id')
    op.drop_index(op.f('ix_tenant_invites_code'), table_name='tenant_invites')
    op.drop_table('tenant_invites')
    # ### end Alembic commands ###
